/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "../interface/RooPDF_HiggsAnalysis_DSCB.h"

#include "RooAbsReal.h"
#include "RooArgList.h"

#include <cmath>
#include <iomanip>
#include <sstream>
#include <stdexcept>

ClassImp(RooPDF_HiggsAnalysis_DSCB);

RooPDF_HiggsAnalysis_DSCB::RooPDF_HiggsAnalysis_DSCB(const char* name,
                                                     const char* title,
                                                     RooAbsReal& _x,
                                                     RooAbsReal& _realHiggsMass,
                                                     RooAbsReal& _branch_ratio_1,
                                                     RooAbsReal& _branch_ratio_2,
                                                     RooAbsReal& _norm_Systematic,
                                                     RooAbsReal& _shape_Systematic,
                                                     const std::vector<std::vector<double>>& _signal_params,
                                                     bool _multiplyBy2)
    : RooPDF_HiggsAnalysis_Base(
          name, title, _x, _realHiggsMass, _branch_ratio_1, _branch_ratio_2, _norm_Systematic, _shape_Systematic),
      signal_params(_signal_params),
      multiplyBy2(_multiplyBy2) {
  LimitSetting::ShapeSystematics::validateParameterMatrix(signal_params, "DSCB nominal parameters");
}

RooPDF_HiggsAnalysis_DSCB::RooPDF_HiggsAnalysis_DSCB(
    const char* name,
    const char* title,
    RooAbsReal& _x,
    RooAbsReal& _realHiggsMass,
    RooAbsReal& _branch_ratio_1,
    RooAbsReal& _branch_ratio_2,
    RooAbsReal& _norm_Systematic,
    const RooArgList& _shape_Systematics,
    const std::vector<std::string>& _systematic_names,
    const LimitSetting::ShapeSystematics::ParameterMatrix& _signal_params,
    const LimitSetting::ShapeSystematics::ParameterCube& _systematic_up_params,
    const LimitSetting::ShapeSystematics::ParameterCube& _systematic_down_params,
    bool _multiplyBy2)
    : RooPDF_HiggsAnalysis_Base(
          name, title, _x, _realHiggsMass, _branch_ratio_1, _branch_ratio_2, _norm_Systematic, _shape_Systematics),
      signal_params(_signal_params),
      systematic_up_params(_systematic_up_params),
      systematic_down_params(_systematic_down_params),
      systematic_names(_systematic_names),
      multiplyBy2(_multiplyBy2) {
  LimitSetting::ShapeSystematics::validateSystematicInputs(
      signal_params, systematic_names, systematic_up_params, systematic_down_params);

  if (shape_Systematics.size() != systematic_names.size()) {
    throw std::invalid_argument("Number of DSCB nuisance variables does not match number of systematics");
  }
  for (std::size_t index = 0; index < shape_Systematics.size(); ++index) {
    if (dynamic_cast<const RooAbsReal*>(shape_Systematics.at(index)) == nullptr) {
      throw std::invalid_argument("DSCB shape-systematic arguments must all derive from RooAbsReal");
    }
  }
}

RooPDF_HiggsAnalysis_DSCB::RooPDF_HiggsAnalysis_DSCB(RooPDF_HiggsAnalysis_DSCB const& other, const char* name)
    : RooPDF_HiggsAnalysis_Base(other, name),
      signal_params(other.signal_params),
      systematic_up_params(other.systematic_up_params),
      systematic_down_params(other.systematic_down_params),
      systematic_names(other.systematic_names),
      multiplyBy2(other.multiplyBy2) {}

double RooPDF_HiggsAnalysis_DSCB::nuisanceValue(std::size_t systematic) const {
  const auto* nuisance = dynamic_cast<const RooAbsReal*>(shape_Systematics.at(systematic));
  if (nuisance == nullptr) {
    throw std::runtime_error("A DSCB shape-systematic dependency is not a RooAbsReal");
  }
  return nuisance->getVal();
}

double RooPDF_HiggsAnalysis_DSCB::effectiveCoefficient(std::size_t parameter, std::size_t coefficient) const {
  if (parameter >= signal_params.size() || coefficient >= signal_params.at(parameter).size()) {
    throw std::out_of_range("DSCB parameter/coefficient index is out of range");
  }

  const double nominal = signal_params.at(parameter).at(coefficient);
  double result = nominal;
  for (std::size_t systematic = 0; systematic < systematic_names.size(); ++systematic) {
    result +=
        LimitSetting::ShapeSystematics::interpolate(nominal,
                                                    systematic_up_params.at(systematic).at(parameter).at(coefficient),
                                                    systematic_down_params.at(systematic).at(parameter).at(coefficient),
                                                    nuisanceValue(systematic)) -
        nominal;
  }
  return result;
}

double RooPDF_HiggsAnalysis_DSCB::parameterizationValue(std::size_t parameter, double higgsMass) const {
  const double p0 = effectiveCoefficient(parameter, 0);
  const double p1 = effectiveCoefficient(parameter, 1);
  const double p2 = effectiveCoefficient(parameter, 2);
  // FitFunction::PowerLaw has exactly three coefficients.  Older model
  // builders sometimes appended fit errors to each row; those are metadata,
  // not an additive fourth coefficient.
  return p0 * std::pow(higgsMass - p1, p2);
}

std::string RooPDF_HiggsAnalysis_DSCB::coefficientFormula(std::size_t parameter,
                                                          std::size_t coefficient,
                                                          std::size_t nuisanceArgumentOffset) const {
  const double nominal = signal_params.at(parameter).at(coefficient);
  std::ostringstream expression;
  expression << std::setprecision(17) << '(' << nominal;
  for (std::size_t systematic = 0; systematic < systematic_names.size(); ++systematic) {
    const std::size_t argument = nuisanceArgumentOffset + systematic;
    const double upShift = systematic_up_params.at(systematic).at(parameter).at(coefficient) - nominal;
    const double downShift = systematic_down_params.at(systematic).at(parameter).at(coefficient) - nominal;
    expression << "+0.5*(@" << argument << "+abs(@" << argument << "))*(" << upShift << ')' << "+0.5*(-@" << argument
               << "+abs(@" << argument << "))*(" << downShift << ')';
  }
  expression << ')';
  return expression.str();
}

RooFormulaVar RooPDF_HiggsAnalysis_DSCB::signal_norm(std::string channel_name) {
  constexpr std::size_t nuisanceArgumentOffset = 2;
  std::string normExpression = "@1*(" + coefficientFormula(6, 0, nuisanceArgumentOffset) + "*pow(@0-" +
                               coefficientFormula(6, 1, nuisanceArgumentOffset) + "," +
                               coefficientFormula(6, 2, nuisanceArgumentOffset) + ")";
  normExpression += ")";

  RooArgList arguments(*realHiggsMass.absArg(), *norm_Systematic.absArg());
  for (const auto* nuisance : shape_Systematics) {
    arguments.add(*nuisance);
  }

  const std::string name = channel_name + "_norm";
  return RooFormulaVar(name.c_str(), name.c_str(), normExpression.c_str(), arguments);
}

double RooPDF_HiggsAnalysis_DSCB::evaluate() const {
  const double higgsMass = realHiggsMass;
  const double alpha_l = parameterizationValue(0, higgsMass);
  const double alpha_h = parameterizationValue(1, higgsMass);
  const double n_l = parameterizationValue(2, higgsMass);
  const double n_h = parameterizationValue(3, higgsMass);
  const double mean = parameterizationValue(4, higgsMass);
  const double sigma = parameterizationValue(5, higgsMass);
  const double norm = parameterizationValue(6, higgsMass);
  const double t = (x - mean) / sigma;

  double result;
  const double fact1TLessMinosAlphaL = alpha_l / n_l;
  const double fact2TLessMinosAlphaL = (n_l / alpha_l) - alpha_l - t;
  const double fact1THhigerAlphaH = alpha_h / n_h;
  const double fact2THigherAlphaH = (n_h / alpha_h) - alpha_h + t;

  if (-alpha_l <= t && alpha_h >= t) {
    result = std::exp(-0.5 * t * t);
  } else if (t < -alpha_l) {
    result = std::exp(-0.5 * alpha_l * alpha_l) * std::pow(fact1TLessMinosAlphaL * fact2TLessMinosAlphaL, -n_l);
  } else {
    result = std::exp(-0.5 * alpha_h * alpha_h) * std::pow(fact1THhigerAlphaH * fact2THigherAlphaH, -n_h);
  }

  const double lowTailNorm = (n_l / std::abs(alpha_l)) / (n_l - 1.0) * std::exp(-0.5 * alpha_l * alpha_l);
  const double highTailNorm = (n_h / std::abs(alpha_h)) / (n_h - 1.0) * std::exp(-0.5 * alpha_h * alpha_h);
  const double root2 = std::sqrt(2.0);
  const double gaussianNormA = std::erf(std::abs(alpha_l / root2)) + std::erf(std::abs(alpha_h / root2));
  const double gaussianNormB = std::sqrt(std::acos(-1.0) / 2.0) * gaussianNormA;
  const double functionNormalization = 1.0 / (sigma * (gaussianNormB + lowTailNorm + highTailNorm));

  const double multiplicity = multiplyBy2 ? 2.0 : 1.0;
  return multiplicity * norm * functionNormalization * result;
}
