/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#include "../interface/RooPDF_HiggsAnalysis_DSCB.h"

#include "RooArgList.h"

#include <cmath>

const int ALPHA_L = 1;
const int ALPHA_H = 0;
const int N_L = 5;
const int N_H = 4;
const int MEAN = 2;
const int SIGMA = 3;
const int NORM = 6;

ClassImp(RooPDF_HiggsAnalysis_DSCB);

RooPDF_HiggsAnalysis_DSCB::RooPDF_HiggsAnalysis_DSCB(
    const char *name,
    const char *title,
    RooAbsReal& _x,
    RooAbsReal& _realHiggsMass,
    RooAbsReal& _branch_ratio_1,
    RooAbsReal& _branch_ratio_2,
    RooAbsReal& _norm_Systematic,
    RooAbsReal& _shape_Systematic,
    const std::vector<std::vector<double>>& _signal_params,
    bool _multiplyBy2)
    : RooPDF_HiggsAnalysis_Base(name, title, _x, _realHiggsMass, _branch_ratio_1, _branch_ratio_2,
                                _norm_Systematic, _shape_Systematic),
      signal_params(_signal_params),
      multiplyBy2(_multiplyBy2)
{
}

RooPDF_HiggsAnalysis_DSCB::RooPDF_HiggsAnalysis_DSCB(
    const char *name,
    const char *title,
    RooAbsReal& _x,
    RooAbsReal& _realHiggsMass,
    RooAbsReal& _branch_ratio_1,
    RooAbsReal& _branch_ratio_2,
    RooAbsReal& _norm_Systematic,
    RooAbsReal& _shape_Systematic,
    const std::vector<std::vector<double>>& _signal_params,
    const std::vector<std::vector<double>>& _systematic_up_params,
    const std::vector<std::vector<double>>& _systematic_down_params,
    bool _multiplyBy2)
    : RooPDF_HiggsAnalysis_Base(name, title, _x, _realHiggsMass, _branch_ratio_1, _branch_ratio_2,
                                _norm_Systematic, _shape_Systematic),
      signal_params(_signal_params),
      systematic_up_params(_systematic_up_params),
      systematic_down_params(_systematic_down_params),
      multiplyBy2(_multiplyBy2)
{
}

RooPDF_HiggsAnalysis_DSCB::RooPDF_HiggsAnalysis_DSCB(
    RooPDF_HiggsAnalysis_DSCB const &other,
    const char *name)
    : RooPDF_HiggsAnalysis_Base(other, name),
      signal_params(other.signal_params),
      systematic_up_params(other.systematic_up_params),
      systematic_down_params(other.systematic_down_params),
      multiplyBy2(other.multiplyBy2)
{
}

RooFormulaVar RooPDF_HiggsAnalysis_DSCB::signal_norm(std::string channel_name)
{
    const auto& params = signal_params.at(NORM);
    std::string formula = "@1 * " + std::to_string(params.at(0)) +
                          " * pow(@0 - " + std::to_string(params.at(1)) +
                          ", " + std::to_string(params.at(2)) + ")";

    return RooFormulaVar((channel_name + "_norm").c_str(),
                         (channel_name + "_norm").c_str(),
                         formula.c_str(),
                         RooArgList(*realHiggsMass.absArg(), *norm_Systematic.absArg()));
}

double RooPDF_HiggsAnalysis_DSCB::interpolate(double nominal, double up, double down) const
{
    const double delta = shape_Systematic;

    if (delta >= 0)
    {
        return nominal + delta * (up - nominal);
    }

    return nominal + (-delta) * (down - nominal);
}

double RooPDF_HiggsAnalysis_DSCB::evaluatePowerLaw(int parameter) const
{
    const auto& nominal = signal_params.at(parameter);

    double a0 = nominal.at(0);
    double a1 = nominal.at(1);
    double a2 = nominal.at(2);

    if (!systematic_up_params.empty() && !systematic_down_params.empty())
    {
        const auto& up = systematic_up_params.at(parameter);
        const auto& down = systematic_down_params.at(parameter);

        a0 = interpolate(nominal.at(0), up.at(0), down.at(0));
        a1 = interpolate(nominal.at(1), up.at(1), down.at(1));
        a2 = interpolate(nominal.at(2), up.at(2), down.at(2));
    }

    return a0 * std::pow(realHiggsMass - a1, a2);
}

double RooPDF_HiggsAnalysis_DSCB::evaluate() const
{
    const double alpha_l = evaluatePowerLaw(ALPHA_L);
    const double alpha_h = evaluatePowerLaw(ALPHA_H);
    const double n_l = evaluatePowerLaw(N_L);
    const double n_h = evaluatePowerLaw(N_H);
    const double mean = evaluatePowerLaw(MEAN);
    const double sigma = evaluatePowerLaw(SIGMA);

    const auto& normParams = signal_params.at(NORM);
    const double norm = normParams.at(0) * std::pow(realHiggsMass - normParams.at(1), normParams.at(2));

    const double t = (x - mean) / sigma;

    double result;
    const double lowFactor1 = alpha_l / n_l;
    const double lowFactor2 = (n_l / alpha_l) - alpha_l - t;
    const double highFactor1 = alpha_h / n_h;
    const double highFactor2 = (n_h / alpha_h) - alpha_h + t;

    if (-alpha_l <= t && t <= alpha_h)
    {
        result = std::exp(-0.5 * t * t);
    }
    else if (t < -alpha_l)
    {
        result = std::exp(-0.5 * alpha_l * alpha_l) * std::pow(lowFactor1 * lowFactor2, -n_l);
    }
    else
    {
        result = std::exp(-0.5 * alpha_h * alpha_h) * std::pow(highFactor1 * highFactor2, -n_h);
    }

    const double lowTailNorm = (n_l / std::abs(alpha_l)) / (n_l - 1) * std::exp(-0.5 * alpha_l * alpha_l);
    const double highTailNorm = (n_h / std::abs(alpha_h)) / (n_h - 1) * std::exp(-0.5 * alpha_h * alpha_h);
    const double root2 = std::sqrt(2.0);
    const double gaussianRange = std::erf(std::abs(alpha_l / root2)) + std::erf(std::abs(alpha_h / root2));
    const double gaussianNorm = std::sqrt(std::acos(-1.0) / 2.0) * gaussianRange;
    const double functionNormalization = 1.0 / (sigma * (gaussianNorm + lowTailNorm + highTailNorm));

    if (multiplyBy2)
    {
        return 2 * norm * functionNormalization * result;
    }

    return norm * functionNormalization * result;
}
