/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooPDF_HiggsAnalysis_DSCB_h
#define RooPDF_HiggsAnalysis_DSCB_h

#include "RooAbsReal.h"
#include "RooFormulaVar.h"
#include "RooPDF_HiggsAnalysis_Base.h"

#include <string>
#include <vector>

class RooPDF_HiggsAnalysis_DSCB : public RooPDF_HiggsAnalysis_Base
{
public:
    RooPDF_HiggsAnalysis_DSCB() {}

    RooPDF_HiggsAnalysis_DSCB(const char *name, const char *title,
                              RooAbsReal& _x,
                              RooAbsReal& _realHiggsMass,
                              RooAbsReal& _branch_ratio_1,
                              RooAbsReal& _branch_ratio_2,
                              RooAbsReal& _norm_Systematic,
                              RooAbsReal& _shape_Systematic,
                              const std::vector<std::vector<double>>& _signal_params,
                              bool _multiplyBy2);

    RooPDF_HiggsAnalysis_DSCB(const char *name, const char *title,
                              RooAbsReal& _x,
                              RooAbsReal& _realHiggsMass,
                              RooAbsReal& _branch_ratio_1,
                              RooAbsReal& _branch_ratio_2,
                              RooAbsReal& _norm_Systematic,
                              RooAbsReal& _shape_Systematic,
                              const std::vector<std::vector<double>>& _signal_params,
                              const std::vector<std::vector<double>>& _systematic_up_params,
                              const std::vector<std::vector<double>>& _systematic_down_params,
                              bool _multiplyBy2);

    RooPDF_HiggsAnalysis_DSCB(RooPDF_HiggsAnalysis_DSCB const &other, const char *name = nullptr);

    RooFormulaVar signal_norm(std::string channel_name) override;
    TObject* clone(const char *newname) const override
    {
        return new RooPDF_HiggsAnalysis_DSCB(*this, newname);
    }

protected:
    std::vector<std::vector<double>> signal_params;
    std::vector<std::vector<double>> systematic_up_params;
    std::vector<std::vector<double>> systematic_down_params;
    bool multiplyBy2 = false;

    double interpolate(double nominal, double up, double down) const;
    double evaluatePowerLaw(int parameter) const;
    double evaluate() const override;

private:
    ClassDefOverride(RooPDF_HiggsAnalysis_DSCB, 2)
};

#endif
