/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooPDF_HiggsAnalysis_DSCB_h
#define RooPDF_HiggsAnalysis_DSCB_h

#include "RooPDF_HiggsAnalysis_Base.h"
#include "ShapeSystematics.h"

#include "RooAbsReal.h"
#include "RooArgList.h"

#include <cstddef>
#include <string>
#include <vector>

class RooPDF_HiggsAnalysis_DSCB : public RooPDF_HiggsAnalysis_Base {
public:
  // ROOT needs a default constructor when materialising dictionaries and
  // workspace objects.  Keep the flag deterministic even before a streamed
  // object has been populated.
  RooPDF_HiggsAnalysis_DSCB() : multiplyBy2(false) {}
  // Compatibility constructor for existing macros.  Because it contains no
  // up/down values, the old generic shape variable intentionally has no
  // effect on the nominal PDF.
  RooPDF_HiggsAnalysis_DSCB(const char* name,
                            const char* title,
                            RooAbsReal& _x,
                            RooAbsReal& _realHiggsMass,
                            RooAbsReal& _branch_ratio_1,
                            RooAbsReal& _branch_ratio_2,
                            RooAbsReal& _norm_Systematic,
                            RooAbsReal& _shape_Systematic,
                            const std::vector<std::vector<double>>& _signal_params,
                            bool multiplyBy2);

  // General constructor: one zero-centred nuisance per named systematic,
  // with absolute up/down alternate coefficient values.
  RooPDF_HiggsAnalysis_DSCB(const char* name,
                            const char* title,
                            RooAbsReal& _x,
                            RooAbsReal& _realHiggsMass,
                            RooAbsReal& _branch_ratio_1,
                            RooAbsReal& _branch_ratio_2,
                            RooAbsReal& _norm_Systematic,
                            const RooArgList& _shape_Systematics,
                            const std::vector<std::string>& _systematic_names,
                            const LimitSetting::ShapeSystematics::ParameterMatrix& _signal_params,
                            const LimitSetting::ShapeSystematics::ParameterCube& _systematic_up_params,
                            const LimitSetting::ShapeSystematics::ParameterCube& _systematic_down_params,
                            bool multiplyBy2);

  RooPDF_HiggsAnalysis_DSCB(RooPDF_HiggsAnalysis_DSCB const& other, const char* name = nullptr);
  RooFormulaVar signal_norm(std::string channel_name) override;

  double effectiveCoefficient(std::size_t parameter, std::size_t coefficient) const;
  double parameterizationValue(std::size_t parameter, double higgsMass) const;
  const std::vector<std::string>& systematicNames() const { return systematic_names; }

  TObject* clone(const char* newname) const override { return new RooPDF_HiggsAnalysis_DSCB(*this, newname); }

protected:
  LimitSetting::ShapeSystematics::ParameterMatrix signal_params;
  LimitSetting::ShapeSystematics::ParameterCube systematic_up_params;
  LimitSetting::ShapeSystematics::ParameterCube systematic_down_params;
  std::vector<std::string> systematic_names;
  bool multiplyBy2;

  double evaluate() const override;

private:
  double nuisanceValue(std::size_t systematic) const;
  std::string coefficientFormula(std::size_t parameter,
                                 std::size_t coefficient,
                                 std::size_t nuisanceArgumentOffset) const;

  ClassDefOverride(RooPDF_HiggsAnalysis_DSCB, 2)
};

#endif  // RooPDF_HiggsAnalysis_DSCB_h
