/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "../interface/RooPDF_HiggsAnalysis_Base.h"

ClassImp(RooPDF_HiggsAnalysis_Base);

RooPDF_HiggsAnalysis_Base::RooPDF_HiggsAnalysis_Base(const char* name,
                                                     const char* title,
                                                     RooAbsReal& _x,
                                                     RooAbsReal& _realHiggsMass,
                                                     RooAbsReal& _branch_ratio_1,
                                                     RooAbsReal& _branch_ratio_2,
                                                     RooAbsReal& _norm_Systematic,
                                                     RooAbsReal& _shape_Systematic)
    : RooAbsPdf(name, title),
      x("x", "x", this, _x),
      realHiggsMass("realHiggsMass", "realHiggsMass", this, _realHiggsMass),
      branch_ratio_1("branch_ratio_1", "branch_ratio_1", this, _branch_ratio_1),
      branch_ratio_2("branch_ratio_2", "branch_ratio_2", this, _branch_ratio_2),
      norm_Systematic("norm_Systematic", "norm_Systematic", this, _norm_Systematic),
      shape_Systematics("shape_Systematics", "shape_Systematics", this) {
  shape_Systematics.add(_shape_Systematic);
}

RooPDF_HiggsAnalysis_Base::RooPDF_HiggsAnalysis_Base(const char* name,
                                                     const char* title,
                                                     RooAbsReal& _x,
                                                     RooAbsReal& _realHiggsMass,
                                                     RooAbsReal& _branch_ratio_1,
                                                     RooAbsReal& _branch_ratio_2,
                                                     RooAbsReal& _norm_Systematic,
                                                     const RooArgList& _shape_Systematics)
    : RooAbsPdf(name, title),
      x("x", "x", this, _x),
      realHiggsMass("realHiggsMass", "realHiggsMass", this, _realHiggsMass),
      branch_ratio_1("branch_ratio_1", "branch_ratio_1", this, _branch_ratio_1),
      branch_ratio_2("branch_ratio_2", "branch_ratio_2", this, _branch_ratio_2),
      norm_Systematic("norm_Systematic", "norm_Systematic", this, _norm_Systematic),
      shape_Systematics("shape_Systematics", "shape_Systematics", this) {
  shape_Systematics.add(_shape_Systematics);
}

RooPDF_HiggsAnalysis_Base::RooPDF_HiggsAnalysis_Base(RooPDF_HiggsAnalysis_Base const& other, const char* name)
    : RooAbsPdf(other, name),
      x("x", this, other.x),
      realHiggsMass("realHiggsMass", this, other.realHiggsMass),
      branch_ratio_1("branch_ratio_1", this, other.branch_ratio_1),
      branch_ratio_2("branch_ratio_2", this, other.branch_ratio_2),
      norm_Systematic("norm_Systematic", this, other.norm_Systematic),
      shape_Systematics(this, other.shape_Systematics) {}

double RooPDF_HiggsAnalysis_Base::evaluate() const { return 1.0; }
