/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooPDF_HiggsAnalysis_Base_h
#define RooPDF_HiggsAnalysis_Base_h

#include "RooAbsPdf.h"
#include "RooArgList.h"
#include "RooListProxy.h"
#include "RooRealProxy.h"
#include "RooAbsReal.h"
#include "RooFormulaVar.h"

#include <string>

class RooPDF_HiggsAnalysis_Base : public RooAbsPdf {
public:
  RooPDF_HiggsAnalysis_Base() {}
  RooPDF_HiggsAnalysis_Base(const char* name,
                            const char* title,
                            RooAbsReal& _x,
                            RooAbsReal& _realHiggsMass,
                            RooAbsReal& _branch_ratio_1,
                            RooAbsReal& _branch_ratio_2,
                            RooAbsReal& _norm_Systematic,
                            RooAbsReal& _shape_Systematic);
  RooPDF_HiggsAnalysis_Base(const char* name,
                            const char* title,
                            RooAbsReal& _x,
                            RooAbsReal& _realHiggsMass,
                            RooAbsReal& _branch_ratio_1,
                            RooAbsReal& _branch_ratio_2,
                            RooAbsReal& _norm_Systematic,
                            const RooArgList& _shape_Systematics);
  RooPDF_HiggsAnalysis_Base(RooPDF_HiggsAnalysis_Base const& other, const char* name = nullptr);

  double evaluate() const override;
  virtual RooFormulaVar signal_norm(std::string channel_name) = 0;

protected:
  RooRealProxy x;
  RooRealProxy realHiggsMass;
  RooRealProxy branch_ratio_1;
  RooRealProxy branch_ratio_2;
  RooRealProxy norm_Systematic;
  RooListProxy shape_Systematics;

private:
  ClassDefOverride(RooPDF_HiggsAnalysis_Base, 2)
};

#endif  // RooPDF_HiggsAnalysis_Base_h
